FROM node:18 AS build

WORKDIR /usr/src/client

COPY package.json ./
COPY yarn.lock ./

RUN yarn

COPY . .

RUN yarn build


FROM nginx
COPY ngnix.conf /etc/nginx/conf.d/default.conf
COPY --from=build /usr/src/client/dist /usr/share/nginx/html