version: '3'
services:
  dev_server:
    container_name: dev_server
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
      - FRONT_END='http://localhost:5173'
      - JWT_SECRET=MyAweSomeJWTSecretThatNoOneCanGuess
      - TOKEN_ALIVE_TIME=1h
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=admin
      - HOST=mongo_db_dev
    volumes:
      - ./backend/src:/usr/src/app/src
    command: yarn start:dev

  mongo_db_dev:
    container_name: mongo_db_dev
    image: mongo:7.0.5
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=masterDB
    volumes:
      - mongo_dev:/data/configdb
      - mongo_dev:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    ports:
      - '27017:27017'
    restart: always

  dev_client:
    container_name: dev_client
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/usr/src/client/src
    ports:
      - '5174:5174'
    environment:
      - REGISTER_URL='http://localhost:3001/api/auth/register'
      - LOGIN_URL='http://localhost:3001/api/auth/login'
    command: yarn dev --port 5174

volumes:
  mongo_dev:
